[Add] Adds buckshot shuffler
MysticalFaceLesS/Shiptest pull request #1024
Opened 2024-10-04 11:49 UTC by MrRomainzZ

ПР добавляет пермешиватель бакшотов. Работает как коробка патронов, но с возможностью перемешивать пули при нажатии на пробел (кнопка по умолчанию).

Перемешиватель можно распечатать на автолате за 4 листа железа во вкладке "Безопасность". Им можно собирать использованные и заряженные бакшоты.

Позволяет играть в "Buckshot Roulette" без участия третьего человека.

<details>
<summary>Видео с изменениями</summary>
(В видео была допущена ошибка. По правилам игры выше, после пустого выстрела в себя ты продолжаешь ход)

https://github.com/user-attachments/assets/4ccd4759-1ce5-4f9c-9a53-95e7d8b4f858

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-10-04 15:16 UTC, RalseiDreemuurr commented on code/modules/projectiles/ammunition/_ammunition.dm
> -				if (bullet.BB)
При EDIT-е коркокода старый код не вырезается, а комментится. Плюс нет закрывающего эдитпоста

2024-10-04 15:19 UTC, MrRomainzZ commented on code/modules/projectiles/ammunition/_ammunition.dm
> -				if (bullet.BB)
Мне не нужно было вырезать или комментить. Я расширил проверку. Закрывающий эдитпост сделаю

2024-10-04 15:19 UTC, MrRomainzZ commented
Предложка была в виде друга в дискорде. И не знаю, что плохого в "штучке"

2024-10-04 15:20 UTC, RalseiDreemuurr commented on code/modules/projectiles/ammunition/_ammunition.dm
> -				if (bullet.BB)
Всё равно старый кодкод должен быть закомменчен и добавлен в ЭДИТ по правилам нашей модульности 
![image](https://github.com/user-attachments/assets/77afdd64-ff33-4785-8c1a-86986307c08d)

2024-10-04 15:22 UTC, RalseiDreemuurr commented
> Предложка была в виде друга в дискорде. И не знаю, что плохого в "штучке"

Я не говорю, что плохо. Просто у нас ПР-ы, не проходящие предложки или не находящиеся в тасках просто так не принимаются. В общем, решай вопрос с хэдкодером

2024-10-04 15:31 UTC, MrRomainzZ commented on code/modules/projectiles/ammunition/_ammunition.dm
> -				if (bullet.BB)
О, шаблон. Сейчас поправлю

2024-10-04 15:47 UTC, RalseiDreemuurr submitted a review, later dismissed

2024-10-05 23:10 UTC, MrCat15352 approved these changes

2024-10-05 23:12 UTC, MrCat15352 requested changes

2024-10-05 23:12 UTC, MrCat15352 commented on code/modules/projectiles/boxes_magazines/_box_magazine.dm
> +	var/shuffler = FALSE
Это можно было сделать и в модуле

2024-10-05 23:12 UTC, MrCat15352 commented
Конфликты + у тебя ещё

2024-10-06 02:04 UTC, MrRomainzZ commented on code/modules/projectiles/boxes_magazines/_box_magazine.dm
> +	var/shuffler = FALSE
день оверрайда....

2024-10-06 16:16 UTC, MrCat15352 approved these changes

2024-10-06 16:17 UTC, RalseiDreemuurr approved these changes

2024-10-06 16:17 UTC, merged