Lanius
MysticalFaceLesS/Shiptest pull request #1037
Opened 2024-10-06 12:54 UTC by FinkRLD

Новая игровая раса - Ланиусы

![image](https://github.com/user-attachments/assets/65311efe-8c84-4483-af63-ab3e778507a9)

Подробнее ТЗ по ссылке: https://discord.com/channels/1100198143456465067/1288232842907877528

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-10-06 13:32 UTC, RalseiDreemuurr submitted a review, later dismissed

2024-10-06 16:15 UTC, MrCat15352 requested changes

2024-10-06 16:15 UTC, MrCat15352 commented on code/__DEFINES/~mod_celadon/lanius.dm
> +
Лишняя строка

2024-10-06 16:15 UTC, MrCat15352 commented on code/datums/components/footstep.dm
> +
Лишняя строка в коркоде. Зачем?

2024-10-06 16:15 UTC, MrCat15352 commented on code/datums/components/footstep.dm
> +			if(islanius(parent)) //[CELADON - ADD] LANIUS
Где оформление?

2024-10-06 16:15 UTC, MrCat15352 commented on code/datums/components/footstep.dm
> +			playsound(T, pick(H.dna.species.special_step_sounds), 10, TRUE, falloff_distance = 1)
Изменение коркода, где оформление?

2024-10-06 16:15 UTC, MrCat15352 commented on code/game/machinery/scan_gate.dm
> +					// [CELADON-ADD] - TAJARA - LANIUS
Не тире а через запятую. Сейчас это выглядит так: ИД таяра с коментарием что это Ланиусы

2024-10-06 16:15 UTC, MrCat15352 commented on code/modules/client/preferences.dm
> +			if(!istype(pref_species, /datum/species/lanius))
Это новая строка кода, где оформление?

2024-10-06 16:15 UTC, MrCat15352 commented on code/modules/client/preferences.dm
> +			if(!istype(pref_species, /datum/species/lanius))
Это EDIT

2024-10-06 16:15 UTC, MrCat15352 commented on code/modules/mob/living/carbon/human/species.dm
> +					//[CELADON - ADD] - LANIUS
Пробел между слешами и скобкой забыл

2024-10-06 16:15 UTC, MrCat15352 commented on code/modules/mob/living/carbon/human/species.dm
> +					//[CELADON - ADD] - LANIUS
и лишние пробелы вокруг тире

2024-10-06 16:15 UTC, MrCat15352 commented on code/modules/mob/living/carbon/human/species.dm
> +					//[CELADON - ADD] - LANIUS
Аналогично, плюс слеша нету внутри скобки

2024-10-06 16:15 UTC, MrCat15352 commented on config/game_options.txt
> +## [CELADON-ADD] - TAJARA - Lanius
не тире а запятая

2024-10-06 16:15 UTC, MrCat15352 commented on mod_celadon/lanius/README.md
> +## НАЗВАНИЕ_МОДА
`НАЗВАНИЕ_МОДА` заменить `Ланиусы`

2024-10-06 16:15 UTC, MrCat15352 commented on code/modules/mob/living/carbon/human/species.dm
> +					//[CELADON - ADD] - LANIUS
`CELADON_LANIUS` а у тебя `LANIUS`

2024-10-06 16:15 UTC, MrCat15352 commented on code/modules/mob/living/carbon/human/species.dm
> +					//[CELADON - ADD] - LANIUS
`CELADON_LANIUS` а у тебя `LANIUS`

2024-10-06 16:15 UTC, MrCat15352 commented on code/game/machinery/scan_gate.dm
> +					// [CELADON-ADD] - TAJARA - LANIUS
`CELADON_LANIUS` а у тебя `LANIUS`

2024-10-06 16:15 UTC, MrCat15352 commented on code/datums/components/footstep.dm
> +			if(islanius(parent)) //[CELADON - ADD] LANIUS
`CELADON_LANIUS` а у тебя `LANIUS`

2024-10-06 16:15 UTC, MrCat15352 commented on mod_celadon/lanius/README.md
> +- code\__DEFINES\~mod_celadon\lanius.dm
Не те слеши

2024-10-06 16:15 UTC, MrCat15352 commented on mod_celadon/lanius/README.md
> +- code\__DEFINES\~mod_celadon\lanius.dm
Не те слеши

2024-10-06 16:15 UTC, MrCat15352 commented on mod_celadon/lanius/code/bodyparts.dm
> +/obj/item/organ/ears/lanius
Если это пока пустые заготовки на будущее, то предлагаю указать хотя бы по параметру в `icon` на `icon = null`

2024-10-06 16:15 UTC, MrCat15352 commented on mod_celadon/lanius/code/food.dm
> +var/ration=list(/obj/item/stack/sheet/metal,
Форматирование не? Равно бы обрамить пробелами

2024-10-06 16:15 UTC, MrCat15352 commented on mod_celadon/lanius/code/food.dm
> +	.=..()
пробелы не?

2024-10-06 16:15 UTC, MrCat15352 commented on mod_celadon/lanius/code/food.dm
> +		'mod_celadon/_storge_sounds/sound/lanius/bp_sfx_RockMan_Thud3_01.ogg'), rand(10,50), TRUE)		SEND_SIGNAL(src, COMSIG_FOOD_EATEN, M, user)
Что за огромный пробел между Скобкой и отправкой сигнала?

2024-10-06 16:15 UTC, MrCat15352 commented on mod_celadon/lanius/code/lanius.dm
> +
Лишние строки убрать

2024-10-06 16:15 UTC, MrCat15352 commented on mod_celadon/lanius/code/lanius.dm
> +	inherent_biotypes = MOB_HUMANOID|MOB_MINERAL
Пробелы добавить вокруг сепоратора

2024-10-06 16:15 UTC, MrCat15352 commented on mod_celadon/mod_celadon.dme
> +
Лишняя строка

2024-10-07 18:06 UTC, RalseiDreemuurr approved these changes

2024-10-08 12:42 UTC, MrCat15352 requested changes

2024-10-08 12:42 UTC, MrCat15352 commented on code/datums/components/footstep.dm
> +			if(islanius(parent)) //[CELADON-ADD] - CELADON_LANIUS
Почему комент идед ПОСЛЕ а не ДО и на строку выше?

2024-10-08 12:42 UTC, MrCat15352 commented on code/datums/components/footstep.dm
> +				//return
Ты это закомментил?

2024-10-08 12:42 UTC, MrCat15352 commented on code/datums/components/footstep.dm
> +			//playsound(T, pick(H.dna.species.special_step_sounds), 50, TRUE, falloff_distance = 1)
Это операция CELADON-EDIT

2024-10-08 12:42 UTC, MrCat15352 commented on code/modules/client/preferences.dm
> +			if(!istype(pref_species, /datum/species/lanius)) // [CELADON - EDIT] LANIUS
Почему ПОСЛЕ а не ДО?

2024-10-08 12:42 UTC, MrCat15352 commented on code/modules/client/preferences.dm
> +					dat += "</table><br>"
А где конец блока изменений?

2024-10-08 12:42 UTC, MrCat15352 commented on code/modules/mob/living/carbon/human/species.dm
> +					// [/CELADON-ADD] - CELADON_LANIUS
Зачем айди указал? Он не нужен, итак в самом начале есть айди и хватит

2024-10-09 12:05 UTC, RalseiDreemuurr commented on code/datums/components/footstep.dm
> +				//return
Да, это его код, который он закомментил

2024-10-09 12:12 UTC, RalseiDreemuurr commented on code/modules/client/preferences.dm
> +					dat += "</table><br>"
Сделано

2024-10-09 12:29 UTC, MrCat15352 approved these changes

2024-10-09 12:30 UTC, RalseiDreemuurr approved these changes

2024-10-09 12:31 UTC, merged