смешная овермапочка
MysticalFaceLesS/Shiptest pull request #1045
Opened 2024-10-07 00:47 UTC by Discozavisim

ПР делает что-то глупое

Добавляет:
- Попиксельные шаттлы (шаттлы двигаются по пикселям)
- Реалистичные вектора (0-360)
- Визуал (визуализация вектора движения и следа траектории полёта)
- Может быть немного говнокод (я писал это в 2 часа ночи после пьянки, просто ткните пальчиком где не нравится я перепишу)
- Разделение heading (направление носа) от course (вектор истинного движения)
- Новые спрайты

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

https://github.com/user-attachments/assets/fd00ae6f-553e-4655-b1df-f3cdb2042cf5

![image](https://github.com/user-attachments/assets/d8b04351-71ea-4374-b837-40b29a0aeb3b)

2024-10-08 21:54 UTC, Discozavisim commented
Можно качать у себя тестить

2024-10-08 21:55 UTC, Discozavisim commented
https://github.com/user-attachments/assets/bebbfd53-5317-42a5-8aa3-44a6fd92d7aa


https://github.com/user-attachments/assets/1345499b-6239-43d3-b1d9-a8c6772b51bf

2024-10-11 16:22 UTC, Discozavisim commented
https://github.com/user-attachments/assets/61658919-3153-413e-8ff5-17d85d6cdd4a

обновил спрайтики

2024-10-15 03:09 UTC, MrCat15352 commented
Напиши, когда посчитаешь что ПР в целом готовый

2024-10-15 10:50 UTC, molnizz approved these changes, later dismissed

2024-10-15 10:57 UTC, MrCat15352 requested changes

2024-10-15 10:57 UTC, MrCat15352 commented on code/game/gamemodes/meteor/meteors.dm
> +// /proc/spawn_meteor(list/meteortypes, datum/virtual_level/vlevel, padding = MAP_EDGE_PAD)
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/helm.dm
> +	// .["heading"] = dir2text(current_ship.get_heading()) || "None"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/helm.dm
> +	// [CELADON-ADD] - OVERMAP ARPA - Это вагабонд насрал
Отличный айди...

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/helm.dm
> +		// sensor_range = 4
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/objects/event_datum.dm
> +	// token_icon_state = "nebula"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/objects/event_datum.dm
> +//	token.light_color = "#c053f3"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/objects/star.dm
> +//	token.pixel_y = -32
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/overmap_token.dm
> +		// for(var/turf/T in view(4, get_turf(src)))
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
> +	//  icon_state = "globe_2"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
> +	// icon_state = "globe_2"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
> +	// icon_state = "globe_2"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
> +	// icon_state = "globe_2"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
> +	// icon_state = "globe_2"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
> +	//	color = "#c6b597"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
> +	//	color = "#a9883e"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
>  	mapgen = /datum/map_generator/planet_generator/waste
А где конец блока `// [/CELADON-EDIT]` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
> +	//	color = COLOR_DARK_MODERATE_ORANGE
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
> +	//	color = COLOR_PURPLE
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/planets/planet_types.dm
> -	icon_state = "globe"
А где блок об изменении?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/ships/controlled_ship_datum.dm
> +// /datum/overmap/ship/controlled/tick_move()
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/ships/ship_datum.dm
> +	// token_icon_state = "ship"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/ships/ship_datum.dm
> +	//		deltimer(movement_callback_id, SSovermap_movement)
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/ships/ship_datum.dm
> +//		movement_callback_id = null //just in case
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/ships/ship_datum.dm
> +	// token.update_icon_state()
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/ships/ship_datum.dm
> +	//	movement_callback_id = addtimer(CALLBACK(src, PROC_REF(tick_move)), timer, TIMER_STOPPABLE, SSovermap_movement)
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/ships/ship_datum.dm
> +	// return "[add_leading(num2text((. / 60) % 60), 2, "0")]:[add_leading(num2text(. % 60), 2, "0")]"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/ships/ship_datum.dm
> +//	adjust_speed(added_velocity["x"], added_velocity["y"])
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on code/modules/overmap/ships/ship_datum.dm
> +		//		token.icon_state = "ship"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on mod_celadon/maps/code/planet_types.dm
> +	// icon_state = "globe"
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on mod_celadon/maps/code/planet_types.dm
> +	//	color = COLOR_PURPLE
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on mod_celadon/maps/code/planet_types.dm
> +	// [CELADON-EDIT] -- OVERMAP ICON -- вагагагагагагагагагагага
почему двойные тире?

2024-10-15 10:57 UTC, MrCat15352 commented on mod_celadon/maps/code/planet_types.dm
> +	// [CELADON-EDIT] -- OVERMAP ICON -- вагагагагагагагагагагага
И тут двойные тире

2024-10-15 10:57 UTC, MrCat15352 commented on mod_celadon/maps/code/planet_types.dm
> +	//	color = COLOR_LIGHT_ORANGE
В конце где `// CELADON-EDIT - ORIGINAL` ?

2024-10-15 10:57 UTC, MrCat15352 commented on shiptest.dme
> +#include "code\controllers\subsystem\overmap_stuff.dm"
Это должно обязательно пррогружаться после сабсистем да?

2024-10-15 16:12 UTC, MrCat15352 requested changes

2024-10-15 16:12 UTC, MrCat15352 commented on mod_celadon/overmap_physics/README.md
> +ID мода: OVERMAP_PHYSICS
`OVERMAP COLLISION, OVERMAP STUFF, OVERMAP ICON, OVERMAP ARPA` вот сюда вписать

2024-10-15 16:14 UTC, MrCat15352 requested changes

2024-10-15 16:14 UTC, MrCat15352 commented on mod_celadon/maps/code/planet_types.dm
> +	// icon_state = "globe"
а, это модпак, тогда это тут не нужно)

2024-10-15 16:14 UTC, MrCat15352 commented on mod_celadon/maps/code/planet_types.dm
> +	// [CELADON-EDIT] -- OVERMAP ICON -- вагагагагагагагагагагага
похуй

2024-10-15 16:14 UTC, MrCat15352 commented on mod_celadon/maps/code/planet_types.dm
> +	//	color = COLOR_PURPLE
это пак! Похуй

2024-10-15 17:59 UTC, Discozavisim commented on mod_celadon/overmap_physics/README.md
> +ID мода: OVERMAP_PHYSICS
начиркал
![image](https://github.com/user-attachments/assets/7dc62fb6-2158-4dbd-9937-daf514adc43d)

2024-10-16 06:04 UTC, MrCat15352 approved these changes
Годен

2024-10-16 18:52 UTC, molnizz approved these changes

2024-10-17 20:33 UTC, merged