Lanius Hotfix
MysticalFaceLesS/Shiptest pull request #1053
Opened 2024-10-10 19:13 UTC by FinkRLD

Реворк внутренних органов, изменен тип лечения на органический, убрал брызги крови при её отсутствии в теле, багфиксы, овверайды коркода
- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-10-10 19:18 UTC, RalseiDreemuurr approved these changes

2024-10-11 04:46 UTC, MrCat15352 requested changes

2024-10-11 04:46 UTC, MrCat15352 commented on code/modules/mob/living/blood.dm
> +	if((NOBLOOD in dna.species.species_traits)) // [CELADON - ADD] LANIUS
Неверное обрамление... Иди читай мануал, как надо правильно

2024-10-11 04:46 UTC, MrCat15352 commented on code/modules/mob/living/blood.dm
> +	if(NOBLOOD in dna.species.species_traits) //  [CELADON - EDIT] Lanius
Неверное обрамление... Иди читай мануал, как надо правильно

2024-10-11 04:46 UTC, MrCat15352 commented on code/modules/mob/living/carbon/human/death.dm
> +			if("lanius")//[CELADON - ADD] LANIUS
Неверное обрамление... Иди читай мануал, как надо правильно

2024-10-11 04:46 UTC, MrCat15352 commented on code/modules/mob/living/carbon/human/death.dm
> +			if("lanius") //[CELADON - ADD] LANIUS
Неверное обрамление... Иди читай мануал, как надо правильно

2024-10-11 04:46 UTC, MrCat15352 commented on code/modules/projectiles/projectile.dm
> -				if(iscarbon(L))
Неверное обрамление... Иди читай мануал, как надо правильно чееее

2024-10-11 09:02 UTC, MrCat15352 commented
Ладно, потом при рефакторинге сам починю все -_-

2024-10-11 09:03 UTC, MrCat15352 approved these changes

2024-10-11 09:03 UTC, merged