nasral
MysticalFaceLesS/Shiptest pull request #1087
Opened 2024-10-17 14:25 UTC by SantaKO1

ПР делает что-то по типу добавления хардсьютов для НТ.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-10-18 03:06 UTC, MrCat15352 requested changes

2024-10-18 03:06 UTC, MrCat15352 commented on code/modules/clothing/spacesuits/hardsuit.dm
> +/obj/item/clothing/head/helmet/space/hardsuit/nanotrasen
Это все можно было сделать через модуль

2024-10-18 03:06 UTC, MrCat15352 commented on code/modules/clothing/spacesuits/hardsuit.dm
> +/obj/item/clothing/head/helmet/space/hardsuit/nanotrasen
Это объект

2024-10-18 03:06 UTC, MrCat15352 commented
Плюсом, отсутствует включение файла пака в главном файле модуля. Ваш пак может вызвать ошибки кода.

2024-10-18 03:29 UTC, arealbeba commented
фиксим

2024-10-18 05:40 UTC, SantaKO1 commented on code/modules/clothing/spacesuits/hardsuit.dm
> +/obj/item/clothing/head/helmet/space/hardsuit/nanotrasen
Уже нашёл куда пак включать

2024-10-18 08:26 UTC, MrCat15352 requested changes

2024-10-18 08:26 UTC, MrCat15352 commented on mod_celadon/nt_hardsuit/README.md
> +## НАЗВАНИЕ_МОДА
ГДЕ НАЗВАНИЕ

2024-10-18 10:39 UTC, SantaKO1 commented on mod_celadon/nt_hardsuit/README.md
> +## НАЗВАНИЕ_МОДА
![image](https://github.com/user-attachments/assets/522109f3-e821-466b-9f9a-79b0703b1526)
не заметил

2024-10-18 11:55 UTC, MrCat15352 requested changes

2024-10-18 11:55 UTC, MrCat15352 commented on mod_celadon/mod_celadon.dme
> +#include "nt_hardsuit/nt_hardsuit.dme"
Почему не по алфавиту расположено?

2024-10-18 11:59 UTC, SantaKO1 commented on mod_celadon/mod_celadon.dme
> +#include "nt_hardsuit/nt_hardsuit.dme"
Починил

2024-10-18 12:11 UTC, arealbeba commented
фиксики работают как часы

2024-10-24 07:36 UTC, MrCat15352 commented
**ЗАМОРОЖЕНО ПО ПРИКАЗУ ВЫСШЕГО ПАЛАЧА**

2024-12-14 22:21 UTC, MrCat15352 commented
@SantaKO1 Конфликты у тебя

2025-04-07 07:24 UTC, closed without merging