Мердж субб шаттла для Шариота+Фикс Утюга
MysticalFaceLesS/Shiptest pull request #1133
Opened 2024-10-22 20:11 UTC by SillyMoff

Мержу субб шаттл+Микро фикс Утюга

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2024-10-31 12:26 UTC, SillyMoff commented
ФАЙНАЛИ закончил

2024-11-01 14:14 UTC, molnizz approved these changes, later dismissed

2024-11-01 14:15 UTC, molnizz commented
@MrCat15352

2024-11-02 08:08 UTC, MrCat15352 requested changes

2024-11-02 08:08 UTC, MrCat15352 commented on _maps/_mod_celadon/configs/nanotrasen_chariot.json
> +	"description": "NTBSV ''Chariot'' - это боевое судно Нанотрейзен, которое сделано в ответ на боевой корабль синдиката ''Креит''. На борту имеется свой десантный корабль, оборудование для работы с ге
Почему судно НТ названо на англ, а синдиката судно на русском?

2024-11-02 08:08 UTC, MrCat15352 commented on _maps/_mod_celadon/configs/nanotrasen_chariot.json
> +	"description": "NTBSV ''Chariot'' - это боевое судно Нанотрейзен, которое сделано в ответ на боевой корабль синдиката ''Креит''. На борту имеется свой десантный корабль, оборудование для работы с ге
Колесница ещё, на рус или на англ?

2024-11-02 09:05 UTC, MrCat15352 approved these changes

2024-11-02 19:25 UTC, molnizz approved these changes

2024-11-02 19:25 UTC, merged