РЕ-Вооружение Кау-Дельта и Комода. Переосмысление Элегии и Тир-Дропа.
MysticalFaceLesS/Shiptest pull request #1171
Opened 2024-11-10 18:26 UTC by SillyMoff

Тир-Дроп: Удалён "танк", заменены названия Капитана и Офицеров, удалён ХОС, полностью заменено оружие: Вместо лазеров дали 2 дизейблера, 1 энергетический арбалет, 1 драгнет, 1 Скаут-Винтовку, лазер кэпа заменен на обычный Антиквар, риги на бронированные ЕВЫ
Комод: Удалена печка, добавлен автолат. Удалены плитники, выданы Медиум-Армор на всё тело. СР Заменены на гидры, помощник кэпа получил ЦР вместо стечкина
Кау: Добавлены МОЛЬКИ. Оружие заменено на: Две ЦР, Одна Скаут-винтовка. Медиум броня заменена на плитники, риги на Бронированные ЕВЫ
Элегия: Переквалифицировалась в Исследовательское судно.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2024-11-10 22:54 UTC, MysticalFaceLesS commented on mod_celadon/_outfits/outfits.dme
Удалить.

2024-11-11 04:00 UTC, MrCat15352 requested changes

2024-11-11 04:00 UTC, MrCat15352 commented on mod_celadon/outfits/README.md
> +## НАЗВАНИЕ_МОДА
Ту т пишется названи твоего модпака вместо `НАЗВАНИЕ_МОДА`

2024-11-11 04:00 UTC, MrCat15352 commented on mod_celadon/outfits/README.md
> +Этот мод служит для возможного добавления оутфита для учёных Киберсана.
Интересно назначение модпака имеющий обобщенное название `outfits`

2024-11-11 04:00 UTC, MrCat15352 commented on mod_celadon/outfits/README.md
> +ID мода: CELADON_OUTFITS
Помяните мои слова, будет путаница в будущем, когда начнете добавлять аутфиты для других. Такое уже было, теже стаф сепаратистов и СФ

2024-11-11 04:01 UTC, MrCat15352 commented
Насчет аутфитов в целом. На данный момент, я не успел произвести рефакторинг модульной папки. Молния начинал что-то делать по этому вопросу недавно. Свяжись с ним, узнай, мб он уже начал структуризовать аутфиты. Потому что аутфиты ейчас разбросаны по частям в разных уголках модульной папки.

2024-11-11 04:04 UTC, MrCat15352 commented
Второй момент, обобщенное название аутфитов и описание его как изменения горлекса. Если ты имел ввиду что аутфиты синдиката будут включены в состав аутфитов, то так и пиши типа: `Этот модпак включает наши аутфиты: синдикат горлексы`

2024-11-11 11:06 UTC, closed without merging