ремап рейнджера + лп уборщик + киберсан на аегисе
MysticalFaceLesS/Shiptest pull request #1173
Opened 2024-11-11 10:10 UTC by arealbeba

ПР делает что-то умное по типу ремапа рейнджера, ремап аегиса под киберсан с удалением сунса и добавляет вещи для лп уборщика рейнджера

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-11-11 11:39 UTC, MrCat15352 requested changes

2024-11-11 11:39 UTC, MrCat15352 commented on mod_celadon/jani_lp/README.md
> +## НАЗВАНИЕ_МОДА JANI_LP
Эх. Вместо НАЗВАНИЕ_МОДА надо было вставить твое название мода

2024-11-11 11:39 UTC, MrCat15352 commented on mod_celadon/jani_lp/README.md
> +ID мода: JANILP
....

2024-11-11 11:39 UTC, MrCat15352 commented on mod_celadon/jani_lp/_jani_lp.dm
> +	author = "SantaKO1"
У тебя есть датум в модпаке. Тут были куча инициализаций. Они нужны когда есть как раз датумы. Что такое датум? Датум это данные. В отличие от объектов которые инициализироваться могут постоянно или временами и повызову, то датумы инициализирутся ТОЛЬКО 1 раз. В коркоде это в момент инициализации сабсистем. У нас же, модульная папка стоит в сааааамом конце Shiptest.dme, а значит датумы не будут инициализированы. Чтобы такое не происходило, есть три конструкции, которые ты снес. 

Возможно датум будет рабоать, но я не обещаю что корректно

2024-11-11 11:39 UTC, MrCat15352 commented on mod_celadon/jani_lp/code/jani_lp.dm
> +/obj/item/clothing/suit/space/hardsuit/ert/lp/jani
У меня доеб к названиям путей. К чему сокращения?

2024-11-11 11:39 UTC, MrCat15352 commented on mod_celadon/jani_lp/README.md
> +ID мода: JANILP
Тут уместнее будет CELADON_JANILP

2024-11-11 11:40 UTC, MrCat15352 commented on mod_celadon/jani_lp/code/jani_lp.dm
> +/obj/item/clothing/suit/space/hardsuit/ert/lp/jani
ну типа janitor, но почему jani?
Ладно у нас понимающий люд, но просто так сокращать там где это не нужно - не следует

2024-11-11 17:09 UTC, arealbeba commented on mod_celadon/jani_lp/code/jani_lp.dm
> +/obj/item/clothing/suit/space/hardsuit/ert/lp/jani
это стандартизация, у всех лп ригов такие сокращения

2024-11-11 17:10 UTC, arealbeba commented on mod_celadon/jani_lp/_jani_lp.dm
> +	author = "SantaKO1"
ниче не понятно, но передам кодеру

2024-11-11 17:12 UTC, arealbeba commented
фиксим

2024-11-18 05:38 UTC, RoyaltyRat approved these changes

2024-11-19 12:03 UTC, arealbeba commented
переделкиваем

2024-11-19 12:03 UTC, closed without merging