bounty: lanius buffs & gun
MysticalFaceLesS/Shiptest pull request #1201
Opened 2024-11-19 11:49 UTC by blasphemk

пр добавляет:
- повышение срезания урона ланиусам с 25% до 35%
- защиту от сварки глазам ланиусов
- встроенная сварка ланиусов, бесконечная, ускоренная, требуется в новых крафтах
- уникальный для ланиусов арбалет с возможностью улучшения конденсатором или маттурбином
- уникальные снаряды для уникального арбалета, доступно в меню крафта
- пачка микроотсылок

в рамках баунти:
https://discord.com/channels/1100198143456465067/1305917397554827294

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-11-22 04:52 UTC, MrCat15352 commented
Шла 2 неделя рассмотрения..

2024-12-29 17:47 UTC, blasphemk commented
жить

2024-12-30 08:54 UTC, blasphemk commented
пр был обновлен

2024-12-30 20:06 UTC, RalseiDreemuurr requested changes
Я обозначил свои требования Шиптест Хэду. Сварки быть не должно. Это не лорно, а надписи на ней просто кринж

2025-01-26 10:53 UTC, Cuildipie commented
ПР закрывается в силу своего аутдейта

2025-01-26 10:53 UTC, closed without merging