Fix: Jetpack module, minor system announce spell. Tweaks: smartfridge for blood.
MysticalFaceLesS/Shiptest pull request #1210
Opened 2024-11-22 16:41 UTC by Yata9arasu

ПР делает что-то умное.
Чинит: Иконки джетпаков, изменяет его, давая анимацию. Так же в анонсе в начале раунда были <> вокруг названия станции. Убраны.

Добавляет: Возможность выбрать плату смартфриджа для крови при настройке платы смартфриджа.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-11-22 17:51 UTC, RoyaltyRat approved these changes, later dismissed

2024-11-23 06:21 UTC, MrCat15352 commented
Я вводил фигурные скобки, чтобы взять по правилам Название сектора типа в кавычки, но кавычки не экранируются нормально. Тебе реально это в глаза бросается? 

Ты с хэдом кодеров обсуждал?

2024-11-23 13:48 UTC, RalseiDreemuurr commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +// [/CELADON-EDIT]
Эдит выполнен не по правилам модульности

2024-11-23 13:49 UTC, RalseiDreemuurr commented on icons/obj/items.dmi
Нельзя менять иконки в коркоде. Если надо менять иконки, выносишь спрайты в модуль, переписываешь пути и нужного объекта в модуль

2024-11-23 13:50 UTC, RalseiDreemuurr commented on icons/obj/tank.dmi
Аналогичная ситуация как с предыдущим

2024-11-23 13:50 UTC, RalseiDreemuurr requested changes
Все комменты расписаны

2024-11-25 14:14 UTC, Yata9arasu commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +// [/CELADON-EDIT]
Перенсёс всё в модуль, чтобы не морочить всем головы

2024-12-01 13:06 UTC, RalseiDreemuurr commented on code/game/objects/items/tanks/jetpack.dm
> +	icon_state = "jetpack_upgrade-on"
Изменения коркода без модульных конструкций

2024-12-05 20:50 UTC, Yata9arasu commented on code/game/objects/items/tanks/jetpack.dm
> +	icon_state = "jetpack_upgrade-on"
Забыл убрать, когда ввёл модульно. Спасибо

2024-12-05 20:50 UTC, Yata9arasu commented on code/game/objects/items/tanks/jetpack.dm
> +	icon_state = "jetpack_upgrade"
Забыл убрать, когда ввёл модульно. Спасибо

2024-12-06 08:09 UTC, MrCat15352 requested changes

2024-12-06 08:09 UTC, MrCat15352 commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +
`// [CELADON-REMOVE] - CELADON_QOL`

2024-12-06 08:09 UTC, MrCat15352 commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +		/obj/machinery/smartfridge/disks = "disks")*/ // CELADON-EDIT - ORIGINAL
После этой строки добавить 
`// [/CELADON-REMOVE]`

2024-12-06 08:09 UTC, MrCat15352 commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +// [CELADON-EDIT] - QoL - Bloodbank circuit added
исправить `QoL` на `CELADON_QOL`

2024-12-06 08:09 UTC, MrCat15352 commented on mod_celadon/fixes/code/jetpack_upgrade.dm
> +//	var/mob/living/carbon/human/cur_user
Зачем тебе комментировать это если оно не будет использоваться? Удаляй

2024-12-06 08:09 UTC, MrCat15352 commented on mod_celadon/fixes/code/jetpack_upgrade.dm
> +//	var/mob/living/carbon/human/cur_user
Зачем тебе комментировать это если оно не будет использоваться? Удаляй

2024-12-07 17:56 UTC, Yata9arasu commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +		/obj/machinery/smartfridge/disks = "disks")*/ // CELADON-EDIT - ORIGINAL
Это оригинальный код, который в случае вставки сверху ломает рабочий код. ДА даже в состоянии комментария

2024-12-07 18:04 UTC, RalseiDreemuurr approved these changes

2024-12-07 18:18 UTC, RoyaltyRat approved these changes

2024-12-07 18:25 UTC, merged