ADD: Barricades
MysticalFaceLesS/Shiptest pull request #1233
Opened 2024-12-03 22:17 UTC by MrCat15352

ПР делает что-то умное, он доделывает таску по барикадам. Надо тестить,надо чинить.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2024-12-03 22:19 UTC, MrCat15352 commented
3 часа ночи, потом потестирую, и починю некоторые моменты

2024-12-04 12:13 UTC, RalseiDreemuurr commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new/datum/stack_recipe("Wooden Half-Barricade", /obj/structure/deployable_barricade/wooden, 5, time = 2 SECONDS, one_per_turf = TRUE, on_floor = TRUE), \
Отсутствует модульная конструкция

2024-12-04 12:14 UTC, RalseiDreemuurr requested changes
Не видел ни спрайтов, ни предложки на это. Жду спрайты мне в ЛС/в канал разработки с пингом меня, пока что не могу это принять

2024-12-04 15:20 UTC, MrCat15352 commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new/datum/stack_recipe("Wooden Half-Barricade", /obj/structure/deployable_barricade/wooden, 5, time = 2 SECONDS, one_per_turf = TRUE, on_floor = TRUE), \
Ага, спасибо, пропустил

2024-12-05 10:11 UTC, RalseiDreemuurr commented on code/__DEFINES/obj_flags.dm
> +#define IGNORE_DENSITY (1<<13) 				//! Can we ignore density when building on this object? (for example, directional windows and grilles)
Отсутствует модульная конструкция

2024-12-05 10:11 UTC, RalseiDreemuurr commented on code/__DEFINES/obj_flags.dm
> +#define FAMILY_HEIRLOOM	(1<<15) // BLUEMOON ADD - выбор вещей из лодаута как family heirloom
"BLUEMOON ADD" 
![image](https://github.com/user-attachments/assets/13694fc2-ddd1-4639-8038-2764d8978784)

2024-12-05 10:12 UTC, RalseiDreemuurr commented on code/datums/armor.dm
> +GLOBAL_LIST_INIT(armor_by_type, generate_armor_type_cache())
Отсутствует модульная конструкция

2024-12-05 10:20 UTC, MrCat15352 reviewed
Поправил

2024-12-07 07:45 UTC, RoyaltyRat approved these changes

2024-12-07 17:18 UTC, merged