BUGFIX: operating table climbing
MysticalFaceLesS/Shiptest pull request #1253
Opened 2024-12-10 08:41 UTC by Samirakis

Позволяет нормально пристёгиваться к операционному столу без танцев с бубном

Видео ДО/ПОСЛЕ прилагаются

https://github.com/user-attachments/assets/fd5219cd-374b-4daf-9183-189ccac9d82b

https://github.com/user-attachments/assets/a78f1e4d-b684-4bd2-b328-5b958e8a488b

- [Х] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [Х] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [Х] Я запускал сервер со своими изменениями локально и все протестировал.

2024-12-14 22:00 UTC, MrCat15352 requested changes

2024-12-14 22:00 UTC, MrCat15352 commented on code/game/objects/structures/tables_racks.dm
> +	climbable = FALSE
Оформи тут по правилам
должно получиться так:
```
// [CELADON-ADD] - CELADON_FIXES - Чиним операционный стол
climbable = FALSE
// [/CELADON-ADD]
```

2024-12-14 22:04 UTC, Samirakis commented on code/game/objects/structures/tables_racks.dm
> +	climbable = FALSE
Не знаком с правилами оформления кода у билда. Скинь, пожалуйста, если они где-то прописаны. Спасибо

2024-12-15 22:44 UTC, PaintedCat commented on code/game/objects/structures/tables_racks.dm
> +	climbable = FALSE
https://github.com/CeladonSS13/Shiptest/tree/beta-dev/mod_celadon#%D0%BA%D0%BE%D0%B4-%D0%BD%D0%B5%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F
Вот ссылка на ридми с якорем на немодульных изменениях

2024-12-17 07:48 UTC, Samirakis commented on code/game/objects/structures/tables_racks.dm
> +	climbable = FALSE
Спасибо, учту на будущее

2024-12-21 14:49 UTC, RoyaltyRat approved these changes

2024-12-21 14:50 UTC, merged