RnD, Cargopad and some vendor restocks in Cargo
MysticalFaceLesS/Shiptest pull request #355
Opened 2024-03-29 21:22 UTC by Yata9arasu

## About The Pull Request
РнД, каргопад, СекТеч и СекДроб в карго

## Why It's Good For The Game
Полезные вещи

## Changelog

:cl:
add: В карго добавлено РнД, взломанное РнД, каргопад, СекТеч и СекДроб вендор рестоки

/:cl:

2024-04-01 17:38 UTC, MrCat15352 requested changes

2024-04-01 17:38 UTC, MrCat15352 commented on mod_celadon/cargo_items/_cargo_items.dm
> +	desc = "Новые позиции в карго"
Подробнее опиши. Тут у тебя три области затрагивается

2024-04-01 18:53 UTC, Yata9arasu commented on mod_celadon/cargo_items/_cargo_items.dm
> +	desc = "Новые позиции в карго"
> Подробнее опиши. Тут у тебя три области затрагивается

Здесь будут не только вещи из моего ПРа, но и остальные вещи, что будут добавляться в карго

2024-04-03 16:37 UTC, MrCat15352 submitted a review, later dismissed

2024-04-03 16:46 UTC, MrCat15352 approved these changes
Переделал структуру в инклуде, добавил разделы для новых инклудов. Сортируемся!

2024-04-03 16:46 UTC, merged