Новый корабль сепаратистов Элизиума
MysticalFaceLesS/Shiptest pull request #394
Opened 2024-04-10 08:11 UTC by NofearNr

Да... он работает на Тесле...дя-дя не надо в щитспавн. Стоит отметить, что на локалке я его не тестил(я пытался честно, я отдельно пробовал скачивать билд, но все равно когда запускаешь, нажимаешь join game оно все белыми квадратиками, я уже и кэш очищал, и уже обновил бьонд до 15 или какой там версии, ну ваще ничё его не берет), ошибок по сути, быть не должно. Точно не должно. Жду вещи зеленых

2024-04-10 17:20 UTC, molnizz commented
Не одобрено, пойдёт на переделку

2024-04-11 03:49 UTC, molnizz requested changes
Переделать описание, убрать непереносные танки с воздухом

2024-04-11 05:30 UTC, MrCat15352 submitted a review, later dismissed

2024-04-11 07:07 UTC, NofearNr commented
Переделал

2024-04-11 20:02 UTC, MrCat15352 commented
@molnizz пока ты не апрувнешь своё ревью, этот ПР так и будет весеть тут

2024-04-12 05:55 UTC, molnizz approved these changes
Иншалах

2024-04-12 05:56 UTC, merged