QF of ships
MysticalFaceLesS/Shiptest pull request #446
Opened 2024-04-22 19:06 UTC by RonninNiko

Еще фикс баланса и пара изминений

2024-04-22 22:13 UTC, MrCat15352 commented
Что за заголовок? Поменять на понятный

2024-04-22 22:14 UTC, MrCat15352 commented
Каких изменений? Подробнее описываем, да и вообще, не по форме

2024-04-22 22:14 UTC, MrCat15352 submitted a review, later dismissed
ПР не соответствует форме оформления

2024-04-23 03:29 UTC, molnizz approved these changes

2024-04-23 03:31 UTC, molnizz requested changes
Ты зачем грав ген удалил?

2024-04-23 03:33 UTC, MrCat15352 commented
> Ты зачем грав ген удалил? 
> 

@RonninNiko

2024-04-23 20:09 UTC, molnizz approved these changes

2024-04-23 20:11 UTC, merged