Tweak: Universal vendor circuit now can be used in Mining vendor
MysticalFaceLesS/Shiptest pull request #482
Opened 2024-05-04 02:39 UTC by Yata9arasu

ПР даёт возможность подкрутить универсальную плату для вендоров с карго в плату для шахтёрского вендомата.

Оффы не приняли по причине "шахтёрский вендомат имба".

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-05-04 05:58 UTC, MrCat15352 requested changes

2024-05-04 05:58 UTC, MrCat15352 commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
>  	custom_premium_price = 100
Неужели тут надо всё комментировать? Ты меняешь ПОЛНОСТЬЮ весь объект? Или его часть?

2024-05-04 05:58 UTC, MrCat15352 commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> -/obj/item/circuitboard/machine/vendor
А эту удалил, и даже не написал что это оригинал

2024-05-04 12:24 UTC, Yata9arasu commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
>  	custom_premium_price = 100
> Неужели тут надо всё комментировать? Ты меняешь ПОЛНОСТЬЮ весь объект? Или его часть?

весь

2024-05-04 12:28 UTC, Yata9arasu commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> -/obj/item/circuitboard/machine/vendor
Случайно строку задел.

2024-05-04 18:48 UTC, MrCat15352 requested changes

2024-05-04 18:48 UTC, MrCat15352 commented on mod_celadon/balance/code/univ-circuit-fix.dm
> +		/obj/machinery/vending/mining_equipment = "Mining Equipment")
@Yata9arasu ты сказал что меняешь его полностью. Но я вижу что ты добавил только одну строчку.

2024-05-05 05:47 UTC, MrCat15352 requested changes

2024-05-05 05:47 UTC, MrCat15352 commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +	// [CELADON-EDIT] - CELADON_BALANCE - Универсальная плата вендоров
Удалить строки 611, 612, 613 и 662. Вернуть кор код на место.

2024-05-05 05:47 UTC, MrCat15352 commented on mod_celadon/balance/code/univ-circuit-fix.dm
> +/obj/item/circuitboard/machine/vendor
Этот файл по сути не нужен.

2024-05-05 05:47 UTC, MrCat15352 commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
>  		/obj/machinery/vending/modularpc = "Deluxe Silicate Selections",
Добавить после этой строки блок из `// [CELADON-ADD] - CELADON_BALANCE - Универсальная плата вендоров` со строкой твоей -> `/obj/machinery/vending/mining_equipment = "Mining Equipment",` а после закрыть `// [/CELADON-ADD]`

2024-05-05 05:47 UTC, MrCat15352 commented on mod_celadon/balance/README.md
> +EDIT: `code\game\objects\items\circuitboards\machine_circuitboards.dm` : `/obj/item/circuitboard/machine/vendor`
Здесь соответственно будет ADD

2024-05-05 20:06 UTC, MrCat15352 requested changes

2024-05-05 20:06 UTC, MrCat15352 commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +		/obj/machinery/vending/mining_equipment = "Mining Equipment")
Вот так будет конфликт. Ибо ты сместил скобку на свою строку.
Сделать надо было вот так:
```
		/obj/machinery/vending/modularpc = "Deluxe Silicate Selections",
// [CELADON-ADD] - CELADON_BALANCE - Универсальная плата вендоров
		/obj/machinery/vending/mining_equipment = "Mining Equipment",
// [/CELADON-ADD]
        /obj/machinery/vending/custom = "Custom Vendor")
```

2024-05-06 11:06 UTC, MrCat15352 approved these changes

2024-05-06 11:06 UTC, merged