Adds Gun Cases. For guns. (#2998)
MysticalFaceLesS/Shiptest pull request #793
Opened 2024-06-28 18:39 UTC by Mirag1993

Adds in gun cases that can hold a variety of guns and magazines, intended for use in cargo and certain ships and ruins. Sprites by retlaw are a work in progress.

Adds in a cool way to store firearms safely, and also its realistic i think. Also requested by apogee.

:cl:
add: Cargo guns and certain guns in ships now come inside cases alongside some magazines, the ammo now comes separately for safety reasons.
/:cl:

---------

ПР делает что-то умное

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2024-06-28 18:59 UTC, Mirag1993 commented
чертовы ошибки , не обьявлен вар capacity

2024-06-28 19:22 UTC, Mirag1993 commented
После мерджа нужно дочинить карты кораблей

2024-06-29 12:46 UTC, MrCat15352 commented
1. Мерж конфликты
2. Почему кор код видоизменен?

2024-06-29 12:47 UTC, MrCat15352 requested changes

2024-06-29 12:47 UTC, MrCat15352 commented on shiptest.dme
> +#include "code\game\objects\items\storage\guncases.dm"
Чегооооо, почему оно тут???

2024-06-29 18:42 UTC, Mirag1993 commented on shiptest.dme
> +#include "code\game\objects\items\storage\guncases.dm"
потому что у нас на кораблях теперь не guncase а guncloset

2024-06-30 22:33 UTC, closed without merging

2024-06-30 22:33 UTC, MysticalFaceLesS commented
ПР оффов был принят и исправлен этим коммитом: https://github.com/CeladonSS13/Shiptest/commit/bb96d594bde0ec5b7d2392596a526fd44e5c788b

ПР закрываю в связи с отсутствием актуальности.