Поставка новых подов на аванпост
MysticalFaceLesS/Shiptest pull request #904
Opened 2024-08-25 11:23 UTC by MrShlepa

Добавление нового Элизиум сапплайпода. Просто centcompod с другим спрайтом.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-08-26 12:52 UTC, MrCat15352 requested changes

2024-08-26 12:52 UTC, MrCat15352 commented on code/__DEFINES/cargo.dm
> +// [CELADON-EDIT]
... а зачем было это делать, если ты мог в конце написать новый под? Да и вообще, дефайны пода надо было создать отдельным файлом

2024-08-26 12:52 UTC, MrCat15352 commented on code/modules/asset_cache/asset_list_items.dm
> +		// [CELADON-EDIT]
забыл слеш внутри скобок добавить

2024-08-26 12:52 UTC, MrCat15352 commented on code/__DEFINES/cargo.dm
> +// [CELADON-EDIT]
также отсутствует слеш внутри скобок

2024-08-26 12:52 UTC, MrCat15352 commented on code/modules/cargo/console.dm
> +	// [CELADON-EDIT]
отсутствует слеш внутри скобок

2024-08-26 12:52 UTC, MrCat15352 commented on code/modules/cargo/console.dm
> +	// [CELADON-EDIT]
да и вообще, это объект, можно было модульно перезаписать переменную

2024-08-26 12:52 UTC, MrCat15352 commented on code/modules/cargo/supplypod.dm
> +	// [CELADON-EDIT]
слеш и это объект, можно было модульно перезаписать переменную

2024-08-26 12:52 UTC, MrCat15352 commented on mod_celadon/elysiumpod/README.md
> +## НАЗВАНИЕ_МОДА
НАЗВАНИЕ_МОДА - тут надо было вставить твое название твоего мода....

2024-08-26 12:52 UTC, MrCat15352 commented on mod_celadon/elysiumpod/_elysiumpod.dm
> +/datum/modpack/example
а вот это херня, у тебя не экзампл, у тебя конкретное название твоего пака идет

2024-08-26 12:52 UTC, MrCat15352 commented on tgui/packages/tgui/interfaces/CentcomPodLauncher.js
> +  { title: 'Elysium' },
я все понимаю, но тгуи не наша территория, и тут нужны комментарии как и в коркоде делаем

2024-08-26 12:56 UTC, MrShlepa commented on code/__DEFINES/cargo.dm
> +// [CELADON-EDIT]
В админ кнопках тогда было бы некрасвио. Точнее в config/launch supplypod в event этот под был бы в конце, наравне с клоунподом и апельсином

2024-08-26 13:05 UTC, MrFloppus commented on code/modules/cargo/supplypod.dm
> +	// [CELADON-EDIT]
Так не получится. У пода нету единого спрайта, там три составляющих: под, дверь, декаль. asset_list_items.dm собирает их воедино

2024-08-26 13:11 UTC, MrShlepa commented on code/__DEFINES/cargo.dm
> +// [CELADON-EDIT]
Так же слеша в readme про модульность не было

2024-08-26 13:19 UTC, MrFloppus commented on code/modules/cargo/console.dm
> +	// [CELADON-EDIT]
Не знаю как

2024-08-27 23:22 UTC, MrCat15352 commented on code/__DEFINES/cargo.dm
> +// [CELADON-EDIT]
И что что не было?

2024-08-27 23:24 UTC, MrCat15352 commented on code/modules/cargo/console.dm
> +	// [CELADON-EDIT]
Ну всмысле? Вот смотри, в коркоде она объявляется так? А ты в модуле берешь и присваиваешь ей другое значение. НО не объявляешь повторно тип
т.е. получится так в модуле
`podType = /obj/structure/closet/supplypod/elysiumpod`

2024-08-27 23:25 UTC, MrCat15352 commented on code/modules/cargo/supplypod.dm
> +	// [CELADON-EDIT]
Так я говорю не за сам файл, а про то что путь можно перезаписать. Хм, надо тестить.

2024-08-28 04:48 UTC, MrShlepa commented on code/__DEFINES/cargo.dm
> +// [CELADON-EDIT]
В инструкции на модульность, в форме на изменения коркода слеша в конце нету. В форме про добавление и удаление он есть

2024-08-28 04:52 UTC, MrShlepa commented on code/__DEFINES/cargo.dm
> +// [CELADON-EDIT]
![Screenshot_68](https://github.com/user-attachments/assets/141bef54-8eee-477a-a316-b5d9df7fcb6a)
![Screenshot_69](https://github.com/user-attachments/assets/73d78aff-54e3-400b-9901-44f080ac4ad9)

2024-08-28 05:08 UTC, MrShlepa commented on code/modules/cargo/console.dm
> +	// [CELADON-EDIT]
Вот так?
![Screenshot_70](https://github.com/user-attachments/assets/78bf2f48-0dba-47ed-9784-78ed00eb09d1)

2024-08-28 10:54 UTC, MrShlepa commented on code/modules/cargo/console.dm
> +	// [CELADON-EDIT]
Ааа вот так вот?
![Screenshot_72](https://github.com/user-attachments/assets/4ff23da4-55a9-490b-9a9f-6bf95c3253be)

2024-08-30 08:19 UTC, MrCat15352 commented on code/__DEFINES/cargo.dm
> +// [CELADON-EDIT]
А в последнем нету слеша)

2024-08-30 08:21 UTC, MrCat15352 commented on code/modules/cargo/console.dm
> +	// [CELADON-EDIT]
да

2024-08-30 08:28 UTC, MrShlepa commented on code/__DEFINES/cargo.dm
> +// [CELADON-EDIT]
Везде есть. Гитхабовский скрин не обновляется

2024-08-30 08:34 UTC, MrCat15352 requested changes

2024-08-30 08:34 UTC, MrCat15352 commented on code/modules/cargo/supplypod.dm
> +	icon = 'mod_celadon/_storge_icons/icons/supplypods.dmi'
Этот оверайд можно тоже модульно сделать. Попробуй вынести в модуль, запустить и глянуть, сработает или нет. Если сработает, то выноси)

2024-08-30 08:48 UTC, MrShlepa commented on code/modules/cargo/supplypod.dm
> +	icon = 'mod_celadon/_storge_icons/icons/supplypods.dmi'
Вроде работает

2024-08-30 09:53 UTC, MrCat15352 approved these changes

2024-08-30 10:15 UTC, RalseiDreemuurr approved these changes

2024-08-30 17:53 UTC, MysticalFaceLesS approved these changes

2024-08-30 17:54 UTC, merged