Новые перила
MysticalFaceLesS/Shiptest pull request #925
Opened 2024-09-04 23:37 UTC by Burbonchik

ПР изменяет спрайт перил, а также даёт возможность наконец-то перелезать через них в обе стороны благодаря мизерному изменению в коде.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-09-05 10:04 UTC, RalseiDreemuurr requested changes
Не модульно, спрайты более менее. Без переделки "по модульности" ПР не будет принят

2024-09-07 12:48 UTC, MrCat15352 requested changes

2024-09-07 12:48 UTC, MrCat15352 commented on icons/obj/railing.dmi
Так делать нельзя. Спрайты не оверайдятся никак. Делаешь следующим образом. Копируешь новый файл, а старый вовзращаешь на место. Новый файл закидываешь `mod_celadon\_storge_icons\icon\obj`

2024-09-07 12:48 UTC, MrCat15352 commented on code/game/objects/structures/railings.dm
Этот файл можно сделать модульно в `mod_celadon/fixes/code`
Создай в этой папке файл `railings.dm` пока

2024-09-07 12:48 UTC, MrCat15352 commented on code/game/objects/structures.dm
Этот файл я уже отредактировал. Но запись об этом надо оставить в `mod_celadon/fixes/README.dm`
Начни его редактировать чтобы он тут отобразился ир я смог тебе показать его

2024-09-15 14:12 UTC, closed without merging