ADD: абордажный телепортер
MysticalFaceLesS/Shiptest pull request #948
Opened 2024-09-15 12:36 UTC by blasphemk

ПР добавляет абордажный телепортер из того самого FTL.

https://github.com/user-attachments/assets/87082799-39f4-494f-b894-8d5cdb1c13e8
(на видео для наглядности я тепнулся на свой же корабль, в игре же можно будет телепортироваться только на чужие)

Немного информации:
- Стоит 10000 кредитов на аванпосте (одиночный абордажник тоже силен, он может спокойно пристыковать вражеский корабль к какой-либо точке, чтобы ждать подмогу)
- При установке на шип, у него на карте появляется иконка телепортера, которую видят все игроки
- Кулдаун: 120 секунд (если телепортер был активирован, но никто не телепортировался, он будет 20 секунд)
- Можно телепортироваться только на корабли, находящиеся на одном космическом тайле с вами
- Можно телепортироваться только одному человеку на телепад, только карбонки и без майнда
- Можно выбрать зону телепортации. Выбирает случайный ОТКРЫТЫЙ турф этой зоны (не стена, но вы можете спокойно попасть в машинерию, окно или в стеклянную канистру с плазмой). В том числе и сразу на мостик.
- Можно телепортироваться на корабли, находящиеся на планетах или каких-либо обьектах.
- Телепортация длится в сумме 6 секунд.

Противодействие:
- При телепортации появляется подсвечиваемый тайл и издается громкий звук
- Приближение корабля с телепортером можно отследить на карте или вовсе миновать, если маневренность и пилотирование хорошо развиты
- ИИ или член экипажа на корабле могут запросто помешать абордажу, также можно расставить ловушки, турели
- Не забываем, что у абордажника нет доступа по кораблю, так что его движение будет проблематично
- Если консоль закрыта на ключ, то бордеру придется ее взламывать определенное время мультитулом, что сопровождается громким анонсом

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-09-15 12:41 UTC, RalseiDreemuurr submitted a review, later dismissed
Спрайты слишком светлые, конечно. Потемнее бы сам пад сделать, может цвета #4C4C4C (76,76,76), в общем, с этим надо поработать, но так меня устраивает

2024-09-15 16:11 UTC, MrCat15352 approved these changes

2024-09-15 16:11 UTC, MrCat15352 commented on mod_celadon/boarding/README.md
> +## НАЗВАНИЕ_МОДА
Сюда вписать название мода

2024-09-15 16:22 UTC, MrCat15352 requested changes

2024-09-15 16:22 UTC, MrCat15352 commented on mod_celadon/boarding/code/boarding.dm
> +	desc = "Used to board enemy shuttles, one person per pad. Instructions? Simple! Take a close distance to shuttle on map, stand on this pad, select it and turn it on. You'd better get ready to kill!"
А почему тут описание на англ, а в другом месте на русском?)

2024-09-15 16:25 UTC, MrCat15352 commented on mod_celadon/boarding/code/boarding.dm
> +	desc = "Used to board enemy shuttles, one person per pad. Instructions? Simple! Take a close distance to shuttle on map, stand on this pad, select it and turn it on. You'd better get ready to kill!"
Короче, все наше можно на русский язык перевести

2024-09-16 05:02 UTC, MrCat15352 commented
Со стороны кода замечаний нет. Поправь только спрайты телепорта, и можем мержить

2024-09-17 19:28 UTC, MrCat15352 approved these changes

2024-09-18 04:11 UTC, RalseiDreemuurr approved these changes

2024-09-18 04:12 UTC, merged