Новый перила, файнали
MysticalFaceLesS/Shiptest pull request #949
Opened 2024-09-15 14:22 UTC by Burbonchik

ПР обновляет спрайт перил, их наложение на окружением и проблему с невозможностью перелезать через них с одной из сторон.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-09-15 16:05 UTC, MrCat15352 approved these changes, later dismissed

2024-09-16 05:10 UTC, MrCat15352 requested changes

2024-09-16 05:10 UTC, MrCat15352 commented on mod_celadon/fixes/code/railings.dm
> +	plane = ABOVE_GAME_PLANE
Так, ну давай смотреть
![image](https://github.com/user-attachments/assets/dc968774-3c36-45a7-ab34-7e4034f836c6)

2024-09-16 05:10 UTC, MrCat15352 commented on mod_celadon/fixes/code/railings.dm
> +	plane = ABOVE_GAME_PLANE
Ты у себя меняешь что? icon 
Плюс ты добавляешь obj_flags и plane
А остальное зачем оверрайдить на точно такое же?

2024-09-16 05:10 UTC, Burbonchik commented on mod_celadon/fixes/code/railings.dm
> +	plane = ABOVE_GAME_PLANE
Я это уже изменил

2024-09-16 05:10 UTC, Burbonchik commented on mod_celadon/fixes/code/railings.dm
> +	plane = ABOVE_GAME_PLANE
Я фикс выложил

2024-09-16 05:13 UTC, MrCat15352 commented on mod_celadon/fixes/code/railings.dm
> +	plane = ABOVE_GAME_PLANE
Мы в модуле меняем лишь те парраметрры, или добавляем, что затрррагивают изменения в объектах, в коде. Оставь icon, obj_flags и plane. А все остальное снеси, оно прям одинаковое

2024-09-16 05:19 UTC, MrCat15352 approved these changes

2024-09-16 05:45 UTC, RalseiDreemuurr approved these changes

2024-09-16 06:03 UTC, MrCat15352 commented
Знакомься, это сквэш) удачи потом чинить ветку

2024-09-16 06:03 UTC, merged