Task: Осовремениваем жукбокс
MysticalFaceLesS/Shiptest pull request #959
Opened 2024-09-18 10:24 UTC by FinkRLD

Из машинерии в сигн-айтем и настенную структуру.

![image](https://github.com/user-attachments/assets/820f0e9c-3da0-4a41-be3c-006e2714135e)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-09-18 11:47 UTC, MrCat15352 requested changes

2024-09-18 11:47 UTC, MrCat15352 commented on mod_celadon/moniq/_moniq.dme
> +#include "code\moniq.dm"
А что за хррень выше? Поясни за все это

2024-09-18 16:53 UTC, MrCat15352 approved these changes

2024-09-19 13:51 UTC, RalseiDreemuurr approved these changes

2024-09-19 15:41 UTC, merged