[Refactoring] Fit Viewport sizes game window to pixel scale
MysticalFaceLesS/Shiptest pull request #973
Opened 2024-09-25 07:32 UTC by MrRomainzZ

Теперь, при вызове функции Fit Viewport, размер экрана будет подгоняться не только под Stretch to Fit, но и под разные уровни размеров пикселей. Это уберёт вертикальные чёрные полосы слева и справа у игрового окна.

https://github.com/user-attachments/assets/ab6584fb-a2b8-4290-9fcc-ca4426c93007

___
- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-09-25 14:01 UTC, MrCat15352 requested changes

2024-09-25 14:01 UTC, MrCat15352 commented on mod_celadon/qol/code/fit_viewport2.dm
> +	set category = "Special Verbs"
Вроде это в модуле. Откуда-то взял весь этот код? Ну просто эти обрамления тут ни к чему)

2024-09-25 14:04 UTC, MrRomainzZ commented on mod_celadon/qol/code/fit_viewport2.dm
> +	set category = "Special Verbs"
Оно не модуль, а изменения кор-кода. В комментарии выше написано откуда брал. "code\modules\client\verbs\ooc.dm". Просто скопировал прок. Сейчас уберу

2024-09-26 05:23 UTC, MrCat15352 commented on mod_celadon/qol/code/fit_viewport2.dm
> +	set category = "Special Verbs"
Получается, ты оверайдишь прок?

2024-09-26 05:24 UTC, MrCat15352 approved these changes

2024-09-26 05:25 UTC, MrCat15352 requested changes

2024-09-26 05:25 UTC, MrCat15352 commented on mod_celadon/qol/code/fit_viewport2.dm
> +// Overrides verb to do what I want
Добавь эту инфу в README.dm в пункт оверрайд. Чтобы уж точно было на виду и ясно что оверайдится

2024-09-26 05:26 UTC, MrCat15352 commented on mod_celadon/qol/code/fit_viewport2.dm
> +	set category = "Special Verbs"
Если так, то сделай пометку в РИДМИ и будет гуд

2024-09-26 07:04 UTC, MrRomainzZ commented on mod_celadon/qol/code/fit_viewport2.dm
> +// Overrides verb to do what I want
Я надеюсь, что "модульность" с записями изменений кор-кода в каждом модуле и неиспользуемой папкой `_master_files` у вас - временное решение...

2024-09-26 10:11 UTC, MrCat15352 approved these changes

2024-09-26 10:11 UTC, merged